# Generated by Django 3.2.8 on 2022-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20220523_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.user'),
        ),
    ]
